import Diff from "@/components/diff";
import Navbar from "@/components/navbar";
import TypedComponents from "@/components/typed";

export const metadata = {
  title: "My App | Landing Page",
  description: "Generated by create next app",
};

export default function Index() {
  return (
    <main>
      <Navbar />
      <Diff />
      <TypedComponents />
      <h1 className="element">Ini halaman index</h1>
    </main>
  );
}
